backend:
  name: gitea
  repo: qingshuige-authors/qingshuige-hugo
  app_id: 2ad8d5ac-e736-42a8-8913-8d91d019397a
  api_root: "https://gitea.qingshuige.ink/api/v1/"
  base_url: "https://gitea.qingshuige.ink/"
  auth_endpoint: "https://gitea.qingshuige.ink/login/oauth/authorize"
  branch: main
media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
